---
- name: "Install pgenv"
  ansible.builtin.git:
    repo: "git@github.com:theory/pgenv.git"
    dest: "{{ local_home }}/.pgenv"

- name: "Install bear"
  community.general.homebrew:
    name: "bear"
    state: latest

- name: "Install pgformatter"
  community.general.homebrew:
    name: "pgformatter"
    state: latest

- name: "Install pspg"
  community.general.homebrew:
    name: "pspg"
    state: latest

- name: "Install pkgconfig"
  community.general.homebrew:
    name: "pkgconf"
    state: latest

- name: "Install icu4c"
  community.general.homebrew:
    name: "icu4c"
    state: latest

- name: "Install openssl"
  community.general.homebrew:
    name: "openssl"
    state: latest

- name: "Install zstd"
  community.general.homebrew:
    name: "zstd"
    state: latest
